// API request/response contracts for the Lexical Resources System.
//
// These mirror the "Example API Contracts" and "API Surface" sections of the
// design. Route handlers (Tasks 7-12) and the client/editor (Tasks 13-19)
// share these shapes so the request/response boundary is type-checked on both
// ends.
//
// Requirements: NFR 1.1, NFR 1.3
import type {
  CategoryViewType,
  CategoryPartOfSpeech,
  EntryType,
  CategoryTree,
  EntryWithRelations,
} from './models';

// ---------------------------------------------------------------------------
// Shared building blocks
// ---------------------------------------------------------------------------

/** A single definition payload. `text` is mixed-language Markdown. */
export interface DefinitionInput {
  text: string;
  partOfSpeech?: string;
}

/** A single example payload. `text` is mixed-language Markdown. */
export interface ExampleInput {
  text: string;
}

/** Field-level validation error reporting used across the API (NFR 3.1). */
export interface FieldError {
  field: string;
  message: string;
}

/** Standard error envelope returned by route handlers on failure. */
export interface ApiErrorResponse {
  error: string;
  fieldErrors?: FieldError[];
}

// ---------------------------------------------------------------------------
// Entry API (R2, R3) — POST/PATCH /api/entries
// ---------------------------------------------------------------------------

/** POST /api/entries */
export interface CreateEntryRequest {
  word: string; // required
  pronunciation?: string;
  categoryId: number; // required (a thesaurus group is just a category)
  entryType?: EntryType;
  notes?: string; // Markdown
  definitions: DefinitionInput[]; // text is Markdown
  examples?: ExampleInput[]; // text is Markdown
  imageIds?: number[]; // previously uploaded images to attach
}

/**
 * PATCH /api/entries/:id
 * All fields optional; only the provided fields are updated. Supplying
 * `definitions`/`examples` replaces the entry's existing set.
 */
export interface UpdateEntryRequest {
  word?: string;
  pronunciation?: string | null;
  categoryId?: number;
  entryType?: EntryType;
  notes?: string | null;
  definitions?: DefinitionInput[];
  examples?: ExampleInput[];
  imageIds?: number[];
  displayOrder?: number;
}

/** Response for entry create/read/update — the fully-populated entry. */
export type EntryResponse = EntryWithRelations;

/** Response for `GET /api/entries?categoryId=`. */
export type EntryListResponse = EntryWithRelations[];

// ---------------------------------------------------------------------------
// Category API (R1, R9) — POST/PATCH/DELETE /api/categories
// ---------------------------------------------------------------------------

/** POST /api/categories */
export interface CreateCategoryRequest {
  name: string; // required
  parentId?: number | null;
  displayOrder?: number;
  viewType?: CategoryViewType;
  partOfSpeech?: CategoryPartOfSpeech;
}

/** PATCH /api/categories/:id — rename / reorder / move. */
export interface UpdateCategoryRequest {
  name?: string;
  parentId?: number | null; // move (cycle-checked server-side)
  displayOrder?: number; // reorder
  viewType?: CategoryViewType;
  partOfSpeech?: CategoryPartOfSpeech | null;
}

/**
 * DELETE /api/categories/:id
 * Q18: when the category contains entries the caller must explicitly choose
 * whether to reassign them or cascade-delete them.
 */
export interface DeleteCategoryRequest {
  mode: 'reassign' | 'cascade';
  reassignToCategoryId?: number; // required when mode === 'reassign'
}

/** Response for `GET /api/categories` — the full nested tree. */
export type CategoryTreeResponse = CategoryTree;

// ---------------------------------------------------------------------------
// Image API (R4) — POST/DELETE /api/images
// ---------------------------------------------------------------------------

/**
 * Response from `POST /api/images`. The multipart upload itself is read from
 * the request body (FormData), so there is no JSON request type. The handler
 * returns the persisted record including the generated thumbnail filename.
 */
export interface ImageUploadResponse {
  id: number;
  filename: string; // original
  thumbnailFilename: string; // generated by Sharp on upload
  altText: string | null;
  fileSize: number;
}

// ---------------------------------------------------------------------------
// Search API (R6) — GET /api/search?q=
// ---------------------------------------------------------------------------

/** A single search hit. `snippet` is plain text extracted from Markdown. */
export interface SearchResult {
  entryId: number;
  word: string;
  categoryId: number;
  categoryName: string;
  snippet: string; // definition excerpt (plain text from Markdown)
}

/** Response for `GET /api/search?q=`. */
export interface SearchResponse {
  query: string;
  results: SearchResult[];
}

// ---------------------------------------------------------------------------
// Export API (R8) — GET /api/export?format=&categoryId=
// ---------------------------------------------------------------------------

/** Supported export formats. */
export type ExportFormat = 'json' | 'csv' | 'markdown';

/** Query parameters for `GET /api/export`. */
export interface ExportRequest {
  format: ExportFormat;
  categoryId?: number; // omit to export the entire collection
}

/**
 * The round-trippable JSON export shape (R8.2, Property 3). Categories are
 * exported as a nested tree; each entry carries its definitions, examples, and
 * images. Auto-generated IDs are retained so the structure is fully
 * reconstructable, but importers may remap them.
 */
export interface ExportedImage {
  filename: string;
  thumbnailFilename: string;
  altText: string | null;
  fileSize: number;
}

export interface ExportedDefinition {
  text: string;
  partOfSpeech: string | null;
  displayOrder: number;
}

export interface ExportedExample {
  text: string;
  displayOrder: number;
}

export interface ExportedEntry {
  word: string;
  pronunciation: string | null;
  entryType: string;
  notes: string | null;
  displayOrder: number;
  definitions: ExportedDefinition[];
  examples: ExportedExample[];
  images: ExportedImage[];
}

export interface ExportedCategory {
  name: string;
  displayOrder: number;
  viewType: string;
  partOfSpeech: string | null;
  entries: ExportedEntry[];
  children: ExportedCategory[];
}

/** Top-level JSON export document. */
export interface ExportDocument {
  version: number;
  exportedAt: string; // ISO-8601 timestamp
  categories: ExportedCategory[];
}

// ---------------------------------------------------------------------------
// Health API (R12) — GET /api/health
// ---------------------------------------------------------------------------

/** Response for `GET /api/health`. */
export interface HealthResponse {
  status: 'ok' | 'error';
  database: 'up' | 'down';
}
